# Generated by Django 5.2 on 2025-04-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("seats", models.PositiveIntegerField()),
                ("color", models.CharField(max_length=50)),
            ],
        ),
    ]
