# Generated by Django 5.2.4 on 2025-08-21 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="vehicle",
            field=models.ForeignKey(
                default=1,
                help_text="The vehicle of the ride",
                on_delete=django.db.models.deletion.CASCADE,
                to="carpool.vehicle",
                verbose_name="vehicle",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="driver",
            field=models.ForeignKey(
                default=1,
                help_text="Driver of the vehicle",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="driver",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ride",
            name="rider",
            field=models.ManyToManyField(
                blank=True,
                help_text="The rider of the ride",
                related_name="rides_as_rider",
                to=settings.AUTH_USER_MODEL,
                verbose_name="rider",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Color of the vehicle",
                max_length=50,
                verbose_name="color",
            ),
        ),
    ]
