# Generated by Django 5.2.4 on 2025-07-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(
                blank=True,
                default="",
                help_text="City of the location",
                max_length=100,
                verbose_name="city",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="street",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Street address of the location",
                max_length=200,
                verbose_name="street",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="zipcode",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Zipcode of the location",
                max_length=10,
                verbose_name="zipcode",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ride",
            name="comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comment about the ride",
                verbose_name="comment",
            ),
            preserve_default=False,
        ),
    ]
