# Generated by Django 5.2.4 on 2025-08-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="color",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Visual description of the vehicle",
                max_length=150,
                verbose_name="visual description",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="geqCO2_per_km",
            field=models.PositiveIntegerField(
                help_text="Number of grams of CO2 emitted per kilometer",
                verbose_name="geqCO2 per km",
                blank=True,
                null=True,
            ),
            preserve_default=False,
        ),
    ]
