# Generated by Django 5.2.4 on 2025-08-26 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0002_ride_vehicle_vehicle_driver_alter_ride_rider_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="driver",
            field=models.ForeignKey(
                help_text="Driver of the vehicle",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                related_query_name="vehicle",
                to=settings.AUTH_USER_MODEL,
                verbose_name="driver",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="name",
            field=models.CharField(
                default="default",
                help_text="Name of the vehicle",
                max_length=50,
                verbose_name="name",
            ),
        ),
    ]
