# Generated by Django 5.2 on 2025-05-02 19:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0002_vehicle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lat",
                    models.FloatField(
                        help_text="Latitude of the location",
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="latitude",
                    ),
                ),
                (
                    "lng",
                    models.FloatField(
                        help_text="Longitude of the location",
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="longitude",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ride",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "Cash"),
                    ("LYF", "Lyf Pay"),
                    ("WIRE", "Wire Transfer"),
                ],
                help_text="The payment method for the ride",
                max_length=10,
                null=True,
                verbose_name="payment method",
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="price",
            field=models.FloatField(
                blank=True,
                help_text="The price of the ride",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="price",
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="rider",
            field=models.ForeignKey(
                blank=True,
                help_text="The rider of the ride",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_as_rider",
                to=settings.AUTH_USER_MODEL,
                verbose_name="rider",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Comment about the ride",
                null=True,
                verbose_name="comment",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                help_text="The driver of the ride",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_as_driver",
                to=settings.AUTH_USER_MODEL,
                verbose_name="driver",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="end_dt",
            field=models.DateTimeField(
                blank=True,
                help_text="The end date and time of the ride",
                null=True,
                verbose_name="end date and time",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="start_dt",
            field=models.DateTimeField(
                blank=True,
                help_text="The start date and time of the ride",
                null=True,
                verbose_name="start date and time",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="color",
            field=models.CharField(
                help_text="Color of the vehicle", max_length=50, verbose_name="color"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="name",
            field=models.CharField(
                help_text="Name of the vehicle", max_length=50, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="seats",
            field=models.PositiveIntegerField(
                help_text="Number of seats in the vehicle",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="seats",
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="end_loc",
            field=models.ForeignKey(
                blank=True,
                help_text="The end location of the ride",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_end_here",
                to="carpool.location",
                verbose_name="end location",
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="start_loc",
            field=models.ForeignKey(
                blank=True,
                help_text="The start location of the ride",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_start_here",
                to="carpool.location",
                verbose_name="start location",
            ),
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Order of the step in the ride",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="order",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Location of the step",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carpool.location",
                        verbose_name="localisation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ride",
            name="steps",
            field=models.ManyToManyField(
                blank=True,
                help_text="The steps of the ride",
                related_name="rides",
                to="carpool.step",
                verbose_name="steps",
            ),
        ),
    ]
