# Generated by Django 4.2.11 on 2025-05-01 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carpool", "0002_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Localisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name="ride",
            name="payment_method",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ride",
            name="price",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ride",
            name="rider",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_as_rider",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_as_driver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "loc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carpool.localisation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ride",
            name="end_loc",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_ends_here",
                to="carpool.localisation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ride",
            name="start_loc",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_start_here",
                to="carpool.localisation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ride",
            name="step",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="carpool.step",
            ),
            preserve_default=False,
        ),
    ]
