# Generated by Django 5.2.4 on 2025-09-01 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0002_remove_vehicle_color_vehicle_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ride",
            options={
                "permissions": [("view_ride_statistics", "Can view ride statistics")]
            },
        ),
    ]
