# Generated by Django 5.2 on 2025-06-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0003_location_ride_payment_method_ride_price_ride_rider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="label",
            field=models.CharField(
                default="",
                help_text="Label for the location",
                max_length=100,
                verbose_name="label",
            ),
            preserve_default=False,
        ),
    ]
