# Generated by Django 5.2.4 on 2025-09-02 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0003_alter_ride_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_users", models.IntegerField(default=0)),
                ("total_rides", models.IntegerField(default=0)),
                ("total_distance", models.FloatField(default=0.0)),
                ("total_co2", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="MonthlyStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                ("total_users", models.IntegerField(default=0)),
                ("total_rides", models.IntegerField(default=0)),
                ("total_distance", models.FloatField(default=0.0)),
                ("total_co2", models.FloatField(default=0.0)),
            ],
            options={
                "unique_together": {("month", "year")},
            },
        ),
    ]
