# Generated by Django 5.2.4 on 2025-09-02 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0004_statistics_monthlystatistics"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monthlystatistics",
            options={
                "verbose_name": "Monthly statistic",
                "verbose_name_plural": "Monthly statistics",
            },
        ),
        migrations.AlterModelOptions(
            name="statistics",
            options={"verbose_name": "Statistic", "verbose_name_plural": "Statistics"},
        ),
    ]
