# Generated by Django 5.2.4 on 2025-09-02 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0005_alter_monthlystatistics_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="seats_offered",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of seats offered for the ride",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="seats offered",
            ),
        ),
    ]
