# Generated by Django 5.2.4 on 2025-09-14 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0006_ride_seats_offered"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                        ],
                        default="PENDING",
                        help_text="Status of the join request",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the reservation was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        help_text="The ride for which the chat request is made",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="carpool.ride",
                        verbose_name="ride",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who made the chat request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
