# Generated by Django 5.2.4 on 2025-09-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0007_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                    ("CANCELED", "Canceled"),
                ],
                default="PENDING",
                help_text="Status of the join request",
                max_length=10,
                verbose_name="status",
            ),
        ),
    ]
