# Generated by Django 5.2.4 on 2025-10-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0008_alter_reservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Comment from the driver about the ride",
                verbose_name="comment",
            ),
        ),
    ]
