# Generated by Django 5.2.4 on 2025-10-18 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0009_alter_ride_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="step",
            name="name",
        ),
    ]
