# Generated by Django 5.2.4 on 2025-11-24 17:52

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0010_remove_step_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="payment_method",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("CASH", "Cash"),
                    ("LYF", "Lyf Pay"),
                    ("WIRE", "Wire Transfer"),
                    ("LYDIA", "Lydia"),
                ],
                default=["CASH"],
                help_text="The payment method for the ride",
                max_length=100,
                verbose_name="payment method",
            ),
        ),
    ]
