# Generated by Django 5.2.4 on 2025-09-22 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usernotificationpreferences",
            options={
                "verbose_name": "User notification preferences",
                "verbose_name_plural": "User notification preferences",
            },
        ),
    ]
