# Generated by Django 5.2 on 2025-07-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_email_verified_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_verification_email_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
