# Generated by Django 5.2.4 on 2025-10-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_usernotificationpreferences_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotificationpreferences",
            name="ride_sharing_suggestion_notification",
            field=models.BooleanField(
                default=True,
                help_text="Receive notifications suggesting to share rides.",
            ),
        ),
    ]
