# Generated by Django 5.2.4 on 2025-10-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_usernotificationpreferences_ride_sharing_suggestion_notification",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("fr", "Français"), ("en", "English")],
                default="fr",
                help_text="Preferred language for the user interface.",
                max_length=10,
            ),
        ),
    ]
