# Generated by Django 5.2.4 on 2026-01-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_multifactorauthenticationdevice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multifactorauthenticationdevice",
            name="totp_secret",
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
