# Generated by Django 5.2.4 on 2026-01-10 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_multifactorauthenticationdevice_totp_secret"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiFactorAuthenticationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enforced_groups",
                    models.ManyToManyField(blank=True, to="auth.group"),
                ),
                (
                    "enforced_users",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Multi-Factor Authentication Policy",
                "verbose_name_plural": "Multi-Factor Authentication Policy",
            },
        ),
    ]
