# Generated by Django 5.2.4 on 2026-01-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_multifactorauthenticationpolicy"),
    ]

    operations = [
        migrations.AddField(
            model_name="multifactorauthenticationpolicy",
            name="enforced_for_staff",
            field=models.BooleanField(
                default=False, help_text="Enforce MFA for all staff users."
            ),
        ),
        migrations.AddField(
            model_name="multifactorauthenticationpolicy",
            name="enforced_for_superusers",
            field=models.BooleanField(
                default=True, help_text="Enforce MFA for all superuser accounts."
            ),
        ),
    ]
