# Generated by Django 5.2.4 on 2025-09-14 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatrequest",
            name="status",
        ),
    ]
