# Generated by Django 5.2.4 on 2025-08-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_read",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether this message has been read by the recipient",
                verbose_name="is read",
            ),
        ),
    ]
