# Generated by Django 5.2.4 on 2025-08-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time when the user was notified about this message (if any)",
                null=True,
                verbose_name="notified at",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="read_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time when the message was read",
                null=True,
                verbose_name="read at",
            ),
        ),
    ]
